### PR TITLE
feat: transform navigation to get links from h2

### PR DESCRIPTION
**Pull request by kptdobe**
- Compute links based on page h2
- Renamed `navigation` block to `toc` block
- Reorganised other blocks headings to limit usage of h2 only to headings that appear in the nav

Fix https://github.com/hlxsites/zeiss/issues/30

Test URLs:
- Before: https://main--zeiss--hlxsites.hlx.page/de/semiconductor-manufacturing-technology/news-und-events/smt-pressemeldung/zeiss-trumpf-und-fraunhofer-mit-deutschem-zukunftspreis-ausgezeichnet
- After: https://toc--zeiss--hlxsites.hlx.page/de/semiconductor-manufacturing-technology/news-und-events/smt-pressemeldung/zeiss-trumpf-und-fraunhofer-mit-deutschem-zukunftspreis-ausgezeichnet

### CODE REVIEW

**Comment by icaraps** [comment]
Weird...  This is what I see

Screen Shot 2022-12-05 at 11 36 54 AM

**Comment by trieloff** [comment]
Same here, is there a commit missing?

**Comment by kptdobe** [comment]
Code sync issue, fixed now.

**Comment by kptdobe** [comment]
We still need a special treatment for the blue button on the right... it points to the "Presskontakt" while on some other pages, it is not there. I am going to add it as a property of the block.

**Comment by icaraps** [comment]
2 links are missing for me ? Do you see it too ?

Screen Shot 2022-12-05 at 11 58 20 AM

**Comment by kptdobe** [comment]
Correct. I have added `Pressbuilder`. `Weiter Articles` will appear when @trieloff will be done with this block.

**Comment by kptdobe** [comment]
Also the CTA button is there too. It is optional and has to be configured manually.

**Pull request merged**
